services:
  - type: web
    name: admin-setting-app
    env: docker
    region: ap-southeast-1 # Singapore, closest to Bangkok
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generate: secret
      - key: API_URL
        value: https://intern-app-backend.onrender.com
