services:
  - type: web
    name: flask-admin-app
    env: docker
    region: ap-southeast-1 # Singapore, closest to Bangkok
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generate: secret
      - key: API_URL
        value: https://automate-internship-screening-backend.onrender.com
